v: 2.6.0
overrideConfig: false
ie:
  - DS_Store
  - less
  - scss
  - js
id:
  - scss
  - .svn
  - .sass-cache
  - fonts
  - icons
cleanPublic: 'true'
patternStates:
  - inprogress
  - inreview
  - complete
styleGuideExcludes: ''
cacheBusterOn: 'true'
exportDir: export
publicDir: ../../../dist/app-pl/pl/
sourceDir: ../../../source/default/
defaultPattern: protons-welcome
defaultShowPatternInfo: false
ishMinimum: '240'
ishMaximum: '2600'
ishControlsHide:
  - hay
lineageMatch: '{%([ ]+)?include( |\()[&quot;\&#039;]([A-Za-z0-9-_]+)[&quot;\&#039;](\))?(.*)%}'
lineageMatchKey: 3
patternExtension: twig
twigDebug: true
twigAutoescape: false
twigDefaultDateFormat: ''
twigDefaultIntervalFormat: ''
twigMacroExt: macro.twig
twigFilterExt: filter.php
twigFunctionExt: function.php
twigTagExt: tag.php
twigTestExt: test.php
styleguideKit: pattern-lab/styleguidekit-twig-default
styleguideKitPath: vendor/pattern-lab/styleguidekit-twig-default
plugins:
  faker:
    enabled: true
    locale: en_US
  twigNamespaces:
    enabled: true
    namespaces:
      protons:
        paths:
          - ../../../source/default/_patterns/00-protons
          - ../../../source/default/_patterns/00-protons/utilities
      atoms:
        paths:
          - ../../../source/default/_patterns/01-atoms
          - ../../../source/default/_patterns/01-atoms/alert
          - ../../../source/default/_patterns/01-atoms/badge
          - ../../../source/default/_patterns/01-atoms/block-title
          - ../../../source/default/_patterns/01-atoms/branding
          - ../../../source/default/_patterns/01-atoms/breadcrumb
          - ../../../source/default/_patterns/01-atoms/button
          - ../../../source/default/_patterns/01-atoms/date
          - ../../../source/default/_patterns/01-atoms/dropdown
          - ../../../source/default/_patterns/01-atoms/grid
          - ../../../source/default/_patterns/01-atoms/highlighted-text
          - ../../../source/default/_patterns/01-atoms/highlighted-text-two
          - ../../../source/default/_patterns/01-atoms/image
          - ../../../source/default/_patterns/01-atoms/list-group
          - ../../../source/default/_patterns/01-atoms/show-more
          - ../../../source/default/_patterns/01-atoms/social-media
          - ../../../source/default/_patterns/01-atoms/svg
          - ../../../source/default/_patterns/01-atoms/tag
      molecules:
        paths:
          - ../../../source/default/_patterns/02-molecules
          - ../../../source/default/_patterns/02-molecules/album
          - ../../../source/default/_patterns/02-molecules/author
          - ../../../source/default/_patterns/02-molecules/block
          - ../../../source/default/_patterns/02-molecules/card
          - ../../../source/default/_patterns/02-molecules/card-slider
          - ../../../source/default/_patterns/02-molecules/carousel
          - ../../../source/default/_patterns/02-molecules/columns
          - ../../../source/default/_patterns/02-molecules/fans-page-card
          - ../../../source/default/_patterns/02-molecules/full-page
          - ../../../source/default/_patterns/02-molecules/header
          - ../../../source/default/_patterns/02-molecules/horizontal-feature
          - ../../../source/default/_patterns/02-molecules/horizontal-list
          - ../../../source/default/_patterns/02-molecules/image-card
          - ../../../source/default/_patterns/02-molecules/info-block
          - ../../../source/default/_patterns/02-molecules/jumbotron
          - ../../../source/default/_patterns/02-molecules/nav
          - ../../../source/default/_patterns/02-molecules/newsletter
          - ../../../source/default/_patterns/02-molecules/pager-infinite-scroll
          - ../../../source/default/_patterns/02-molecules/pagination
          - ../../../source/default/_patterns/02-molecules/related-image
          - ../../../source/default/_patterns/02-molecules/share-links
          - ../../../source/default/_patterns/02-molecules/square-image
          - ../../../source/default/_patterns/02-molecules/vertical-featured
          - ../../../source/default/_patterns/02-molecules/vertical-links
          - ../../../source/default/_patterns/02-molecules/vue-widget
      organisms:
        paths:
          - ../../../source/default/_patterns/03-organisms
          - ../../../source/default/_patterns/03-organisms/accordion
          - ../../../source/default/_patterns/03-organisms/article
          - ../../../source/default/_patterns/03-organisms/card-grid
          - ../../../source/default/_patterns/03-organisms/footer
          - ../../../source/default/_patterns/03-organisms/navbar
      templates:
        paths:
          - ../../../source/default/_patterns/04-templates
          - ../../../source/default/_patterns/04-templates/basic-page
      pages:
        paths:
          - ../../../source/default/_patterns/05-pages
